-- ============================================================
-- 39_performance_dashboard.sql
--
-- Backs the new Performance page (weekly/monthly executive
-- dashboard), modeled on the Report Monthly/Weekly workbook.
--
--  * adds the columns the Weekly Entry tab tracks that
--    weekly_metrics was missing
--  * estimate_status_monthly: the Estimate $ Status block
--    (total / pending / accepted / invoiced / lost, $ and count)
--  * social_followers: the Followers row (month, platform, count)
--  * imports 10 weeks of Weekly Entry (Jul 6 - Sep 7 2026) and
--    3 months of Estimate $ Status (Jul - Sep 2026)
--
-- Run any time. Safe to re-run.
-- ============================================================

alter table weekly_metrics add column if not exists jobs_costed int not null default 0;
alter table weekly_metrics add column if not exists still_needs_costing int not null default 0;
alter table weekly_metrics add column if not exists appointments_set int not null default 0;
alter table weekly_metrics add column if not exists calls_answered int not null default 0;
alter table weekly_metrics add column if not exists missed_calls_returned int not null default 0;
alter table weekly_metrics add column if not exists estimates_accepted int not null default 0;
alter table weekly_metrics add column if not exists estimates_invoiced int not null default 0;
alter table weekly_metrics add column if not exists videos_to_edit int not null default 0;
alter table weekly_metrics add column if not exists videos_ready int not null default 0;
alter table weekly_metrics add column if not exists first_time_calls_answered int not null default 0;
alter table weekly_metrics add column if not exists first_time_calls_missed int not null default 0;

create table if not exists estimate_status_monthly (
  month         date primary key,
  total_amt     numeric(14,2) not null default 0,
  total_ct      int not null default 0,
  pending_amt   numeric(14,2) not null default 0,
  pending_ct    int not null default 0,
  accepted_amt  numeric(14,2) not null default 0,
  accepted_ct   int not null default 0,
  invoiced_amt  numeric(14,2) not null default 0,
  invoiced_ct   int not null default 0,
  lost_amt      numeric(14,2) not null default 0,
  lost_ct       int not null default 0,
  updated_at    timestamptz not null default now()
);
alter table estimate_status_monthly enable row level security;
drop policy if exists team_all on estimate_status_monthly;
create policy team_all on estimate_status_monthly for all to authenticated using (true) with check (true);

create table if not exists social_followers (
  follower_id  uuid primary key default gen_random_uuid(),
  month        date not null,
  platform     text not null,
  followers    int not null default 0,
  unique (month, platform)
);
alter table social_followers enable row level security;
drop policy if exists team_all on social_followers;
create policy team_all on social_followers for all to authenticated using (true) with check (true);

-- weekly entry import
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, review_requests_sent, reviews_received, appointments_set, calls_answered, first_time_calls_answered, first_time_calls_missed) values ('2026-07-09', 7, 37, 25, 3, 0, 0, 0, 0, 0.0, 2, 3, 1, 0, 20, 12, 0) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, review_requests_sent, reviews_received, appointments_set, calls_answered, first_time_calls_answered, first_time_calls_missed) values ('2026-07-16', 10, 34, 50, 7, 0, 0, 2, 2, 25450.46, 5, 3, 1, 0, 42, 14, 6) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, blogs_written, blogs_posted, review_requests_sent, reviews_received, appointments_set, calls_answered, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-07-23', 10, 30, 35, 4, 0, 0, 1, 2, 13625.9, 5, 1, 0, 1, 1, 0, 29, 14, 9, 3) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, blogs_written=excluded.blogs_written, blogs_posted=excluded.blogs_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, review_requests_sent, reviews_received, appointments_set, calls_answered, missed_calls_returned, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-07-30', 10, 25, 29, 6, 0, 0, 1, 0, 0.0, 5, 2, 4, 0, 18, 20, 6, 3, 8, 3) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, missed_calls_returned=excluded.missed_calls_returned, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, estimates_sent, estimates_cancelled, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, blogs_written, blogs_posted, review_requests_sent, final_photos_needed, jobs_costed, still_needs_costing, appointments_set, calls_answered, missed_calls_returned, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-08-06', 10, 51, 29, 4, 24, 0, 2, 0, 1, 0, 0.0, 5, 0, 0, 3, 2, 7, 19, 0, 23, 4, 2, 3, 12, 2) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, estimates_sent=excluded.estimates_sent, estimates_cancelled=excluded.estimates_cancelled, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, blogs_written=excluded.blogs_written, blogs_posted=excluded.blogs_posted, review_requests_sent=excluded.review_requests_sent, final_photos_needed=excluded.final_photos_needed, jobs_costed=excluded.jobs_costed, still_needs_costing=excluded.still_needs_costing, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, missed_calls_returned=excluded.missed_calls_returned, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, estimates_sent, estimates_cancelled, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, review_requests_sent, reviews_received, jobs_costed, still_needs_costing, appointments_set, calls_answered, missed_calls_returned, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-08-13', 10, 50, 36, 4, 4, 1, 1, 0, 3, 1, 20415.66, 5, 2, 2, 7, 17, 9, 31, 4, 5, 8, 19, 2) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, estimates_sent=excluded.estimates_sent, estimates_cancelled=excluded.estimates_cancelled, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, jobs_costed=excluded.jobs_costed, still_needs_costing=excluded.still_needs_costing, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, missed_calls_returned=excluded.missed_calls_returned, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, estimates_sent, estimates_cancelled, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, review_requests_sent, reviews_received, final_photos_needed, jobs_costed, still_needs_costing, appointments_set, calls_answered, missed_calls_returned, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-08-20', 17, 45, 32, 8, 5, 0, 0, 0, 2, 1, 13700.0, 5, 1, 2, 1, 6, 16, 0, 23, 8, 4, 4, 11, 3) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, estimates_sent=excluded.estimates_sent, estimates_cancelled=excluded.estimates_cancelled, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, final_photos_needed=excluded.final_photos_needed, jobs_costed=excluded.jobs_costed, still_needs_costing=excluded.still_needs_costing, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, missed_calls_returned=excluded.missed_calls_returned, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, estimates_sent, estimates_cancelled, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, blogs_written, blogs_posted, review_requests_sent, jobs_costed, still_needs_costing, appointments_set, calls_answered, missed_calls_returned, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-08-27', 9, 25, 34, 6, 3, 1, 0, 0, 1, 1, 8497.75, 5, 0, 0, 0, 14, 10, 0, 27, 6, 2, 5, 11, 3) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, estimates_sent=excluded.estimates_sent, estimates_cancelled=excluded.estimates_cancelled, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, blogs_written=excluded.blogs_written, blogs_posted=excluded.blogs_posted, review_requests_sent=excluded.review_requests_sent, jobs_costed=excluded.jobs_costed, still_needs_costing=excluded.still_needs_costing, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, missed_calls_returned=excluded.missed_calls_returned, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, estimates_sent, estimates_cancelled, design_sent, design_sold, jobs_sold, closed_jobs, closed_revenue, videos_posted, review_requests_sent, reviews_received, jobs_costed, still_needs_costing, appointments_set, calls_answered, missed_calls_returned, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-09-03', 11, 35, 27, 4, 4, 1, 0, 0, 1, 1, 13171.09, 5, 1, 0, 6, 9, 0, 20, 4, 0, 8, 9, 2) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, estimates_sent=excluded.estimates_sent, estimates_cancelled=excluded.estimates_cancelled, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, closed_revenue=excluded.closed_revenue, videos_posted=excluded.videos_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, jobs_costed=excluded.jobs_costed, still_needs_costing=excluded.still_needs_costing, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, missed_calls_returned=excluded.missed_calls_returned, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;
insert into weekly_metrics (week_ending, new_leads, cold_calls_completed, calls_received, calls_missed, estimates_sent, estimates_cancelled, design_sent, design_sold, jobs_sold, closed_jobs, videos_posted, blogs_written, blogs_posted, review_requests_sent, reviews_received, jobs_costed, still_needs_costing, appointments_set, calls_answered, videos_to_edit, videos_ready, first_time_calls_answered, first_time_calls_missed) values ('2026-09-10', 15, 36, 46, 14, 2, 1, 0, 0, 1, 1, 5, 0, 0, 1, 1, 1, 32, 0, 25, 3, 6, 20, 6) on conflict (week_ending) do update set new_leads=excluded.new_leads, cold_calls_completed=excluded.cold_calls_completed, calls_received=excluded.calls_received, calls_missed=excluded.calls_missed, estimates_sent=excluded.estimates_sent, estimates_cancelled=excluded.estimates_cancelled, design_sent=excluded.design_sent, design_sold=excluded.design_sold, jobs_sold=excluded.jobs_sold, closed_jobs=excluded.closed_jobs, videos_posted=excluded.videos_posted, blogs_written=excluded.blogs_written, blogs_posted=excluded.blogs_posted, review_requests_sent=excluded.review_requests_sent, reviews_received=excluded.reviews_received, jobs_costed=excluded.jobs_costed, still_needs_costing=excluded.still_needs_costing, appointments_set=excluded.appointments_set, calls_answered=excluded.calls_answered, videos_to_edit=excluded.videos_to_edit, videos_ready=excluded.videos_ready, first_time_calls_answered=excluded.first_time_calls_answered, first_time_calls_missed=excluded.first_time_calls_missed;

-- estimate $ status by month
insert into estimate_status_monthly (month, total_amt, total_ct, pending_amt, pending_ct, accepted_amt, accepted_ct, invoiced_amt, invoiced_ct, lost_amt, lost_ct) values ('2026-07-01', 403378.97, 24, 75486.34, 4, 8497.75, 1, 57524.3, 5, 261870.58, 14) on conflict (month) do update set total_amt=excluded.total_amt, total_ct=excluded.total_ct, pending_amt=excluded.pending_amt, pending_ct=excluded.pending_ct, accepted_amt=excluded.accepted_amt, accepted_ct=excluded.accepted_ct, invoiced_amt=excluded.invoiced_amt, invoiced_ct=excluded.invoiced_ct, lost_amt=excluded.lost_amt, lost_ct=excluded.lost_ct;
insert into estimate_status_monthly (month, total_amt, total_ct, pending_amt, pending_ct, accepted_amt, accepted_ct, invoiced_amt, invoiced_ct, lost_amt, lost_ct) values ('2026-08-01', 55842.36, 3, 0, 0, 32450.25, 1, 19521.04, 1, 3871.07, 1) on conflict (month) do update set total_amt=excluded.total_amt, total_ct=excluded.total_ct, pending_amt=excluded.pending_amt, pending_ct=excluded.pending_ct, accepted_amt=excluded.accepted_amt, accepted_ct=excluded.accepted_ct, invoiced_amt=excluded.invoiced_amt, invoiced_ct=excluded.invoiced_ct, lost_amt=excluded.lost_amt, lost_ct=excluded.lost_ct;
insert into estimate_status_monthly (month, total_amt, total_ct, pending_amt, pending_ct, accepted_amt, accepted_ct, invoiced_amt, invoiced_ct, lost_amt, lost_ct) values ('2026-09-01', 495034.77, 24, 0, 0, 162194.08, 7, 0, 0, 87612.78, 12) on conflict (month) do update set total_amt=excluded.total_amt, total_ct=excluded.total_ct, pending_amt=excluded.pending_amt, pending_ct=excluded.pending_ct, accepted_amt=excluded.accepted_amt, accepted_ct=excluded.accepted_ct, invoiced_amt=excluded.invoiced_amt, invoiced_ct=excluded.invoiced_ct, lost_amt=excluded.lost_amt, lost_ct=excluded.lost_ct;

-- verify
select
  (select count(*) from weekly_metrics where week_ending >= '2026-07-01') as weeks_imported,
  (select round(sum(calls_received)) from weekly_metrics) as total_calls_received,
  (select count(*) from estimate_status_monthly) as est_status_months,
  (select round(sum(accepted_amt)) from estimate_status_monthly) as total_accepted_dollars;
